import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// add this for nextauth session
import { getServerSession } from "next-auth";
import  SessionProvider from "@/components/SessionProvider";

import "./globals.css";
import Navbar from "@/components/Navbar";
// import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <SessionProvider session={session}> 
          
      <main className="min-h-screen bg-gray-100">
        <Navbar/>
         {children}

      </main>
            </SessionProvider>
      </body>
    </html>
  );
}

// 
      {/* Zoho SalesIQ Script */}

        //    id="zoho-salesiq-script"
        //   src="https://salesiq.zohopublic.com/widget?wc=siq62557ad54c21b37277a8dd7849d3953d65d0fd9fda683bda378576734ae092d8a75584460ae1bd55614fb79fede6731b"
        //   strategy="afterInteractive"
        // />
      //      <Script id="zoho-salesiq-init" strategy="afterInteractive">
      //     {`
      //       window.$zoho = window.$zoho || {};
      //      $zoho.salesiq = $zoho.salesiq || {
      //         ready: function () {
      //         // Optional: do something after SalesIQ is ready
      //         }
      //      };
      //     `}
      //  </Script>

      //  <Script


  